name: environment-vars
on: [push]
env:
  fisk: aborre
jobs:
  hello-world:
    runs-on: ubuntu-latest
    env:
      fugl: g√•s
    steps:
      - name: "Hello World"
        run:  echo "Hello $GITHUB_ACTOR og $MY_ACTION. $fisk $fugl $HusDyr"
        env:
          MY_ACTION: ${{ github.action }} 
          MY_ACTOR: ${{ github.actor }} 
          HusDyr: gris
